Move state: Move state and handlers from Form component to GetDetails component.
FACK1/ReWorks pull request #128
Opened 2019-04-02 07:35 UTC by orjwan98

What I did in this PR:

**client/src/components/GetDetails/index.js**
Moved handlers and state from `Form` to `GetDetails` component and passed them to `Form` as props to be used as they were before. 

**client/src/components/Shared/Form/index.js**
Imported handlers and states from `GetDetails` component to `Form` component through props and passed them as appropriate to be used as they were before. 

**Line 74 and 75**
Commented them out because they rely on state that isn't there anymore. Will take care of it in a bit.

2019-04-02 07:41 UTC, Hadeel-Salamin commented on client/src/components/Shared/Form/index.js
> +        // selected_colors: colors[0],
remove coding comments

2019-04-02 07:42 UTC, jema28 requested changes

2019-04-02 07:42 UTC, jema28 commented on client/src/components/GetDetails/index.js
> +        <Form
Try passing down all state (see below) with {...this.state} and then destructuring them in Form.
```
isOpen={this.state.isOpen}
          selected_itemType={this.state.selected_itemType}
          selected_colors={this.state.selected_colors}
          selected_brands={this.state.selected_brands}
          selected_condition={this.state.selected_condition}
          selected_labelSize={this.state.selected_labelSize}
          selected_age={this.state.selected_age}
          selectedCat={this.state.selectedCat}
          toggleOpen={this.toggleOpen}
          toggleClose={this.toggleClose}
          changeSelected={this.changeSelected}
```

2019-04-02 07:42 UTC, jema28 commented on client/src/components/Shared/Form/index.js
> +    if (this.props.apparel) {
You can destructure apparel and color from props here.

2019-04-02 11:24 UTC, jema28 approved these changes
Working well! 👍nice destructuring.

2019-04-02 11:28 UTC, amanshawar approved these changes

2019-04-03 06:32 UTC, amanshawar approved these changes

2019-04-03 07:03 UTC, Hadeel-Salamin approved these changes
Well done :+1:

2019-04-03 07:04 UTC, FidaaHersh approved these changes

2019-04-03 07:09 UTC, jema28 approved these changes

2019-04-03 07:10 UTC, merged