Continue bb
FACK1/ReWorks pull request #142
Opened 2019-04-04 10:59 UTC by amanshawar

2019-04-04 11:16 UTC, orjwan98 approved these changes

2019-04-07 08:36 UTC, jema28 requested changes

2019-04-07 08:36 UTC, jema28 commented on client/src/components/SignUp/index.js
> +  constructor(props) {
You don't need a constructor habibti.

2019-04-07 08:36 UTC, Hadeel-Salamin commented on client/src/components/GetDetails/index.js
> +            selected_brands: { id: brands[0].id, brandName: brands[0].brandName, name: brands[0].brandName },
you can just say selected_brands: brands[0]

2019-04-07 08:40 UTC, Hadeel-Salamin commented
That's greaaaaaaaaaaaaat

2019-04-07 08:40 UTC, jema28 approved these changes

2019-04-07 08:41 UTC, merged

2019-04-07 08:46 UTC, orjwan98 approved these changes