firx multiple issues
FACK1/ReWorks pull request #190
Opened 2019-04-11 07:25 UTC by amanshawar

filtered color data fix #114 
add colored option  fix #173
change button name fix #172 
add star in get details fix #171

2019-04-11 07:28 UTC, FidaaHersh approved these changes

2019-04-11 07:45 UTC, jema28 requested changes
Half reviewed - please delete all references to the circle 🔴

2019-04-11 07:45 UTC, jema28 commented on client/src/components/Shared/Form/index.js
> +circle = hex => (
Please delete this!

2019-04-11 07:45 UTC, jema28 commented on client/src/components/Shared/Form/form.style.js
> +export const CircleColor = styled.div`
Please delete this.

2019-04-11 07:45 UTC, jema28 commented on client/src/components/Shared/Form/index.js
> +  CircleColor,
Please delete this.

2019-04-11 08:32 UTC, Hadeel-Salamin approved these changes

2019-04-11 08:43 UTC, orjwan98 approved these changes

2019-04-14 07:51 UTC, jema28 requested changes

2019-04-14 07:51 UTC, jema28 commented on client/src/data.json
> +  "colors": [
Replace these colours with his list.

2019-04-14 08:28 UTC, jema28 approved these changes

2019-04-14 08:32 UTC, Hadeel-Salamin approved these changes

2019-04-14 08:40 UTC, merged