add currency #176
FACK1/ReWorks pull request #194
Opened 2019-04-11 08:25 UTC by amanshawar

add currency to price fix #176

2019-04-11 08:34 UTC, FidaaHersh approved these changes

2019-04-11 08:45 UTC, orjwan98 approved these changes

2019-04-14 10:22 UTC, jema28 requested changes

2019-04-14 10:22 UTC, jema28 commented on client/src/components/Shared/Form/index.js
> +            <StyledPriceConatiner>
Spelling error here.

2019-04-14 10:22 UTC, jema28 commented on client/src/components/Shared/Form/form.style.js
> +display: flex;
css indentation pleaaaase!

2019-04-14 10:22 UTC, jema28 commented on client/src/components/Shared/Form/form.style.js
> +	background-color: #FBFBFB;
Too much indentation here?

2019-04-14 10:23 UTC, jema28 commented
Really nice job! 😍Default to pounds, fix indentations and then ready to merge 👍

2019-04-14 10:33 UTC, jema28 approved these changes
👍

2019-04-14 10:34 UTC, merged

2019-04-14 10:34 UTC, Hadeel-Salamin approved these changes