Splash #62
FACK1/ReWorks pull request #63
Opened 2019-03-26 11:33 UTC by orjwan98

for details: see commit history. 
references issue #62

2019-03-26 11:43 UTC, jema28 requested changes
Looking awesome but there are a lot of eslint issues. Please fix these 🍐 

<img width="521" alt="Screenshot 2019-03-26 at 14 43 15" src="https://user-images.githubusercontent.com/25960351/54994530-8a64c900-4fd5-11e9-804a-f9a2d154386a.png">

2019-03-26 11:43 UTC, jema28 commented on client/src/components/SplashPage/splashpage.style.js
> +text-align: center;
Please make sure all these indents are right.

2019-03-26 11:46 UTC, Hadeel-Salamin approved these changes

2019-03-27 06:52 UTC, amanshawar approved these changes

2019-03-27 07:23 UTC, jema28 commented on client/src/components/SplashPage/index.js
> +        <Span>Start by uploading a photo of your item</Span>
There's a full stop missing here.

2019-03-27 07:26 UTC, jema28 commented
Going to merge but the indents need to be fixed in a future PR.

2019-03-27 07:26 UTC, jema28 approved these changes

2019-03-27 07:26 UTC, merged