Items
FACK1/ReWorks pull request #79
Opened 2019-03-28 11:18 UTC by fdo2

Finish working on items list component and it's style

2019-03-28 21:35 UTC, Hadeel-Salamin approved these changes
good job :hibiscus:

2019-03-30 09:01 UTC, Hadeel-Salamin commented on client/src/App.js
>  import Item from './components/Item';
you can remove this line as it never used

2019-03-31 05:56 UTC, jema28 requested changes
Happy with the code but formatting needs work 💄

2019-03-31 05:56 UTC, jema28 commented on client/src/components/ItemList/itemlist.style.js
> +font-size: 20px;
There's still some problems with indentation here :/

2019-03-31 05:56 UTC, jema28 commented on client/src/components/ItemList/index.js
> +          <GButtonContainer><GButton title="EXPORT AS CSV" /></GButtonContainer>
Please put this file in prettier, as there are indentation issues.

2019-03-31 05:58 UTC, amanshawar approved these changes

2019-03-31 06:24 UTC, merged